/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAllowanceRouteImport } from './routes/app.allowance'
import { Route as AppAssetRequestsRouteImport } from './routes/app.asset-requests'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppContractsRouteImport } from './routes/app.contracts'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppHelpdeskRouteImport } from './routes/app.helpdesk'
import { Route as AppLeaveRouteImport } from './routes/app.leave'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppOffboardingRouteImport } from './routes/app.offboarding'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppPayslipsRouteImport } from './routes/app.payslips'
import { Route as AppReimbursementRouteImport } from './routes/app.reimbursement'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSalaryRouteImport } from './routes/app.salary'
import { Route as AppSalaryStructureRouteImport } from './routes/app.salary-structure'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppEmployeesIndexRouteImport } from './routes/app.employees.index'
import { Route as AppEmployeesIdRouteImport } from './routes/app.employees.$id'
import { Route as AppPayrollIndexRouteImport } from './routes/app.payroll.index'
import { Route as AppPayrollRunIdRouteImport } from './routes/app.payroll.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAllowanceRoute = AppAllowanceRouteImport.update({
  id: '/allowance',
  path: '/allowance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetRequestsRoute = AppAssetRequestsRouteImport.update({
  id: '/asset-requests',
  path: '/asset-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpdeskRoute = AppHelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppOffboardingRoute = AppOffboardingRouteImport.update({
  id: '/offboarding',
  path: '/offboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppPayslipsRoute = AppPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppReimbursementRoute = AppReimbursementRouteImport.update({
  id: '/reimbursement',
  path: '/reimbursement',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRoute,
} as any)
const AppSalaryStructureRoute = AppSalaryStructureRouteImport.update({
  id: '/salary-structure',
  path: '/salary-structure',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRunIdRoute = AppPayrollRunIdRouteImport.update({
  id: '/payroll/$runId',
  path: '/payroll/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/allowance': typeof AppAllowanceRoute
  '/app/asset-requests': typeof AppAssetRequestsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/helpdesk': typeof AppHelpdeskRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/offboarding': typeof AppOffboardingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/payslips': typeof AppPayslipsRoute
  '/app/reimbursement': typeof AppReimbursementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/salary-structure': typeof AppSalaryStructureRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/payroll/$runId': typeof AppPayrollRunIdRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/payroll/': typeof AppPayrollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/allowance': typeof AppAllowanceRoute
  '/app/asset-requests': typeof AppAssetRequestsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/helpdesk': typeof AppHelpdeskRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/offboarding': typeof AppOffboardingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/payslips': typeof AppPayslipsRoute
  '/app/reimbursement': typeof AppReimbursementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/salary-structure': typeof AppSalaryStructureRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/payroll/$runId': typeof AppPayrollRunIdRoute
  '/app/employees': typeof AppEmployeesIndexRoute
  '/app/payroll': typeof AppPayrollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/allowance': typeof AppAllowanceRoute
  '/app/asset-requests': typeof AppAssetRequestsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/contracts': typeof AppContractsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/helpdesk': typeof AppHelpdeskRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/me': typeof AppMeRoute
  '/app/offboarding': typeof AppOffboardingRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/payslips': typeof AppPayslipsRoute
  '/app/reimbursement': typeof AppReimbursementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/salary-structure': typeof AppSalaryStructureRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/employees/$id': typeof AppEmployeesIdRoute
  '/app/payroll/$runId': typeof AppPayrollRunIdRoute
  '/app/employees/': typeof AppEmployeesIndexRoute
  '/app/payroll/': typeof AppPayrollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/allowance'
    | '/app/asset-requests'
    | '/app/assets'
    | '/app/attendance'
    | '/app/contracts'
    | '/app/dashboard'
    | '/app/helpdesk'
    | '/app/leave'
    | '/app/me'
    | '/app/offboarding'
    | '/app/onboarding'
    | '/app/payslips'
    | '/app/reimbursement'
    | '/app/reports'
    | '/app/salary'
    | '/app/salary-structure'
    | '/app/settings'
    | '/app/employees/$id'
    | '/app/payroll/$runId'
    | '/app/employees/'
    | '/app/payroll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/allowance'
    | '/app/asset-requests'
    | '/app/assets'
    | '/app/attendance'
    | '/app/contracts'
    | '/app/dashboard'
    | '/app/helpdesk'
    | '/app/leave'
    | '/app/me'
    | '/app/offboarding'
    | '/app/onboarding'
    | '/app/payslips'
    | '/app/reimbursement'
    | '/app/reports'
    | '/app/salary'
    | '/app/salary-structure'
    | '/app/settings'
    | '/app/employees/$id'
    | '/app/payroll/$runId'
    | '/app/employees'
    | '/app/payroll'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/allowance'
    | '/app/asset-requests'
    | '/app/assets'
    | '/app/attendance'
    | '/app/contracts'
    | '/app/dashboard'
    | '/app/helpdesk'
    | '/app/leave'
    | '/app/me'
    | '/app/offboarding'
    | '/app/onboarding'
    | '/app/payslips'
    | '/app/reimbursement'
    | '/app/reports'
    | '/app/salary'
    | '/app/salary-structure'
    | '/app/settings'
    | '/app/employees/$id'
    | '/app/payroll/$runId'
    | '/app/employees/'
    | '/app/payroll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/allowance': {
      id: '/app/allowance'
      path: '/allowance'
      fullPath: '/app/allowance'
      preLoaderRoute: typeof AppAllowanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/asset-requests': {
      id: '/app/asset-requests'
      path: '/asset-requests'
      fullPath: '/app/asset-requests'
      preLoaderRoute: typeof AppAssetRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contracts': {
      id: '/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/helpdesk': {
      id: '/app/helpdesk'
      path: '/helpdesk'
      fullPath: '/app/helpdesk'
      preLoaderRoute: typeof AppHelpdeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leave': {
      id: '/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offboarding': {
      id: '/app/offboarding'
      path: '/offboarding'
      fullPath: '/app/offboarding'
      preLoaderRoute: typeof AppOffboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payslips': {
      id: '/app/payslips'
      path: '/payslips'
      fullPath: '/app/payslips'
      preLoaderRoute: typeof AppPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reimbursement': {
      id: '/app/reimbursement'
      path: '/reimbursement'
      fullPath: '/app/reimbursement'
      preLoaderRoute: typeof AppReimbursementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salary': {
      id: '/app/salary'
      path: '/salary'
      fullPath: '/app/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/salary-structure': {
      id: '/app/salary-structure'
      path: '/salary-structure'
      fullPath: '/app/salary-structure'
      preLoaderRoute: typeof AppSalaryStructureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/': {
      id: '/app/employees/'
      path: '/employees'
      fullPath: '/app/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees/$id': {
      id: '/app/employees/$id'
      path: '/employees/$id'
      fullPath: '/app/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll/': {
      id: '/app/payroll/'
      path: '/payroll'
      fullPath: '/app/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll/$runId': {
      id: '/app/payroll/$runId'
      path: '/payroll/$runId'
      fullPath: '/app/payroll/$runId'
      preLoaderRoute: typeof AppPayrollRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAllowanceRoute: typeof AppAllowanceRoute
  AppAssetRequestsRoute: typeof AppAssetRequestsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpdeskRoute: typeof AppHelpdeskRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMeRoute: typeof AppMeRoute
  AppOffboardingRoute: typeof AppOffboardingRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPayslipsRoute: typeof AppPayslipsRoute
  AppReimbursementRoute: typeof AppReimbursementRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppSalaryStructureRoute: typeof AppSalaryStructureRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppPayrollRunIdRoute: typeof AppPayrollRunIdRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAllowanceRoute: AppAllowanceRoute,
  AppAssetRequestsRoute: AppAssetRequestsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppContractsRoute: AppContractsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpdeskRoute: AppHelpdeskRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMeRoute: AppMeRoute,
  AppOffboardingRoute: AppOffboardingRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPayslipsRoute: AppPayslipsRoute,
  AppReimbursementRoute: AppReimbursementRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppSalaryStructureRoute: AppSalaryStructureRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppPayrollRunIdRoute: AppPayrollRunIdRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
